config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'home/index'
  devise_for :views
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  get 'users/new_customer' => 'users/new_customer'
  post 'users/create_customer' => 'users/create_customer'
  get 'users/list_customers' => 'users/list_customers'

  resources :items, only: %i[new create index]

  resources :orders, only: %i[create index]
  get 'orders/process_order/:id', to: 'orders#process_order'
  post 'orders/remove_order/:id', to: 'orders#remove_order'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true, length: { maximum: 70 }
  has_many :item_orders
  has_many :orders, through: :item_orders

  ITEM_TYPES = { beverages: 'Beverage', burger: 'Burger', sandwich: 'Sandwich' }.freeze
end

app/models/item_order.rb
class ItemOrder < ApplicationRecord
	self.table_name = "items_orders"

  belongs_to :order
  belongs_to :item
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :item_orders
  has_many :items, through: :item_orders
  belongs_to :user

  STATE = { drafted: 'drafted', pending: 'pending', completed: 'completed' }.freeze
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 70 }
  validates :role, presence: true

  has_one :order

  ROLES = { admin: 'admin', customer: 'customer' }.freeze

  def is_customer?
    role == User::ROLES[:customer]
  end

  def is_admin?
    role == User::ROLES[:admin]
  end
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :role, :email, :password) }

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :role, :email, :password, :current_password) }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    return redirect_to new_user_session_path unless user_signed_in?
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def create
    item = Item.new(item_params)
    if item.save
      flash[:success] = 'Item Successfully created'
      redirect_to items_path
    else
      render 'new'
    end
  end

  def item_params
    params.require(:item).permit(:name, :item_type, :price, :discount)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	def index
		if current_user.is_customer?
			@orders = [current_user.order].compact
		else
			@orders = Order.all
		end

		respond_to do |format|
			format.html
		end
	end

  def create
    @item = Item.find(params[:item_id])
    @order = current_user.order || Order.new(user_id: current_user.id, state: Order::STATE[:drafted])
    return redirect_to items_path if [Order::STATE[:completed], Order::STATE[:pending]].include? @order.state
    order_persist = true
    order_persist = @order.save unless @order.persisted?
    if order_persist
    	item_order = ItemOrder.create(item_id: @item.id, order_id: @order.id)
    	if item_order.valid?
	    	flash[:success] = 'Item Added to Order!'
	    else
	    	flash[:notice] = 'Order Failed to Create'
	    end
    end
    redirect_to items_path
  end

  def process_order
  	@order = Order.find(params[:id])
  	@order.state = current_user.is_customer? ? Order::STATE[:pending] : Order::STATE[:completed]
  	if @order.save
  		flash[:success] = 'Order Processed!'
  	else
	    flash[:notice] = 'Order Failed to Proceed'
  	end
  	redirect_to orders_path
  end

  def remove_order
  	return redirect_to orders_path unless current_user.is_customer?

  	@order = Order.find(params[:id])
  	@order.destroy

  	redirect_to orders_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new_customer
  end

  def create_customer
    customer = User.new(user_params)
    if customer.save
      flash[:success] = 'Customer Successfully created'
      redirect_to root_path
    else
      render 'new_customer'
    end
  end

  def list_customers
    return redirect_to root_path if current_user.is_customer?

    @customers = User.all.where(role: User::ROLES[:customer])
  end


  def user_params
    params.require(:user).permit(:name, :email, :role, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
	def calculate_amount items
		discounted_sum = 0
		total_sum = 0
		items.map do |item|
			total_sum += item.price
			discounted_sum += (item.price * item.discount) / 100
		end
		[discounted_sum, total_sum]
	end
end

app/views/home/index.html.erb
<div class="jumbotron">
	<% if current_user.role == User::ROLES[:admin] %>
  	<h1 class="display-4 text-center">Admin Panel</h1>
  <% else %>
  	<h1 class="display-4 text-center">Welcome to Coffee Shop!</h1>
  <% end %>
</div>

app/views/items/index.html.erb
<div class="container">
	<% if @items.present? %>
		<h2>List of Items</h2>
		<table class="table">
		  <thead>
		    <tr>
		      <th scope="col">Name</th>
		      <th scope="col">Type</th>
		      <th scope="col">Price</th>
		      <th scope="col">Discount(%)</th>
		      <th></th>
		    </tr>
		  </thead>
		  <tbody>
		  	<% @items.each do |item| %>
			    <tr>
			      <td><%= item.name %></td>
			      <td><%= Item::ITEM_TYPES[item.item_type.to_sym] %></td>
			      <td><%= item.price %></td>
			      <td><%= item.discount %></td>
			      <% if current_user.role == User::ROLES[:customer] %>
					  	<td><%= link_to 'Add To Order', orders_path(item_id: item), method: :post, class: 'float-right' %></td>
				  	<% end %>
		    </tr>
		    <% end %>
		  </tbody>
		</table>
	<% else %>
		<h2>No Items Available</h2>
	<% end %>
</div

app/views/items/new.html.erb
<div class='container'>
  <h2>New Item</h2>
  <%= form_for :item, url: items_path, method: :post do |f| %>
    
    <div class="field form-group">
      <%= f.label :name %><br />
      <%= f.text_field :name, autofocus: true, autocomplete: "name", class: 'form-control' %>
    </div>

    <div class="field form-group">
      <%= f.label :item_type %><br />
      <%= f.select :item_type, Item::ITEM_TYPES.map{ |key, value| [value, key] }, {}, { class: ' form-control' } %>
    </div>

    <div class="field form-group">
      <%= f.label :price %><br />
      <%= f.number_field :price, min: 0, autofocus: true, class: 'form-control' %>
    </div>

    <div class="field form-group">
      <%= f.label 'Discount (%)' %><br />
      <%= f.number_field :discount, min: 0, autofocus: true, autocomplete: "discount", class: 'form-control' %>
    </div>

    <div class="actions">
      <%= f.submit "Add Item", class: 'btn btn-primary mb-2' %>
    </div>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coffee Shop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if flash[:success].present? %>
      <p class="alert alert-success"><%= flash[:success] %></p>
    <% end %>
    <div class='container-fluid'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/index.html.erb
<div class='container'>
	<% if @orders.present? %>
		<h2>List of Orders</h2>
		<table class="table">
		  <thead>
		    <tr>
		      <th scope="col">#</th>
		      <th scope="col">Status</th>
		      <th scope="col">No of Items</th>
		      <th scope="col">Total Amount</th>
		      <th scope="col">Discounted Amount</th>
		      <th></th>
		      <th></th>
		    </tr>
		  </thead>
		  <tbody>
		  	<% @orders.each do |order| %>
			    <tr>
			      <td><%= order.id %></td>
			      <td><%= order.state.capitalize %></td>
			      <td><%= order.items.count %></td>
			      <% discounted_sum, total_sum = calculate_amount(order.items) %>
			      <td><%= total_sum %></td>
			      <td><%= discounted_sum %></td>
			      <td><%= link_to 'Process Order', "/orders/process_order/#{order.id}" %></td>
			      <% if order.state == Order::STATE[:completed] && current_user.is_customer? %>
			      	<td><%= link_to 'Remove Order', "/orders/remove_order/#{order.id}", method: :post %></td>
			      <% end %>
		    </tr>
		    <% end %>
		  </tbody>
		</table>
	<% else %>
		<h2>No orders Available</h2>
	<% end %>
</div>

app/views/shared/_navbar.html.erb
<% name = current_user.present? ? current_user.name : 'Stranger' %>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Coffee Shop</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <% if user_signed_in? && current_user.role == User::ROLES[:admin] %>
      <li class="nav-item">
          <%= link_to 'Add Customer', users_new_customer_path, class: 'nav-link' %>
      </li>
      <li class="nav-item mr-2">
        <%= link_to 'Customers', users_list_customers_path, class: 'nav-link' %>
      </li>
      <li class="nav-item mr-2">
          <%= link_to 'Add Item', new_item_path, class: 'nav-link' %>
      </li>
      <% end %>
      <% if user_signed_in? %>
        <li class="nav-item mr-2">
          <%= link_to 'Items', items_path, class: 'nav-link' %>
        </li>
        <li class="nav-item mr-2">
          <%= link_to 'Orders', orders_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
    <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item mt-2 mr-2">
              <%= name %>
          </li>
          <li class="nav-item">
              <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
              <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
              <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/users/list_customers.html.erb
<div class="container">
	<% if @customers.present? %>
		<h2>List of Customers</h2>
		<div class="list-group">
			<% @customers.each do |customer| %>
			  <a href="#" class="list-group-item list-group-item-action">
			  	<div class='row'>
			  		<div class='col-md-6'>
				  		<%= customer.name %>
				  	</div>
				  	<div class='col-md-6'>
				  		<span class='float-right'><%= customer.email %></span>
				  	</div>
			  	</div>
			  </a>
		  <% end %>
		</div>
	<% else %>
		<h2>No Customers Available</h2>
	<% end %>
</div

app/views/users/new_customer.html.erb
<div class='container'>
  <h2>New Customer</h2>
  <%= form_for :user, url: users_create_customer_path, method: :post do |f| %>
    
    <div class="field form-group">
      <%= f.label :name %><br />
      <%= f.text_field :name, autofocus: true, autocomplete: "name", class: 'form-control' %>
    </div>

    <div class="field form-group">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control' %>
    </div>
    <%= f.hidden_field :role, value: User::ROLES[:customer] %>

    <div class="field form-group">
      <%= f.label :password %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "new-password", class: 'form-control' %>
    </div>

    <div class="field form-group">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "new-password", class: 'form-control' %>
    </div>

    <div class="actions">
      <%= f.submit "Add Customer", class: 'btn btn-primary mb-2' %>
    </div>
  <% end %>

</div>